### ISSUE TITLE
個人整理的webshell-password，更新了100余個密碼

### ISSUE THREAD

**Issue by makoto56** [TheKingOfDuck/fuzzDicts#10]
平時在web滲透過程中遇到別人的web shell就看一下密碼，如果您的webshell-password裏沒有就添加進去，截止2020年2月19日已更新了100余個密碼。

您的原文本爲15837行，我的版本已更新至15940行，已重新排序並去重。

非常喜歡您的fuzzDic項目，在我web滲透過程中發揮了很大的作用，希望您的項目持續更新並越做越強大！如有我可以幫忙的地方一定盡力！

附：
[webshell-pass.txt](https://github.com/TheKingOfDuck/fuzzDicts/files/4221438/webshell-pass.txt)

**Comment by TheKingOfDuck** [comment]
Got，感谢对项目的支持。
