### ISSUE TITLE
你妈在我手里

### ISSUE THREAD

**Issue by KennyWho** [TheKingOfDuck/fuzzDicts#3]
https://github.com/chrislgarry/Apollo-11/issues/470

孤儿，你妈没了，以后不能让你妈当头牌了，这下你不牛逼了吧。

**Comment by TheKingOfDuck** [comment]
真的服你们这些喷子，我不知情的情况下玩笑性的留了那么一条言论，发现不对后 马上close了的，你妈卖批啊追到这里来
